=== redeskako/Master-JAVA-UNED/alef/UNED_2014/J2SE/Individual/antonio/Oca/xsd/tableroOca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generado con XMLSpy v2013 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Y">
		<xs:complexType/>
	</xs:element>
	<xs:element name="X">
		<xs:complexType/>
	</xs:element>
	<xs:element name="Tipo">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
				<xs:enumeration value="4"/>
				<xs:enumeration value="5"/>
				<xs:enumeration value="6"/>
				<xs:enumeration value="7"/>
				<xs:enumeration value="8"/>
				<xs:enumeration value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TableroOca">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Casilla" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RondasSinJugar">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RepetirTurno" type="xs:boolean"/>
	<xs:element name="IndiceDestino">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="13"/>
				<xs:enumeration value="14"/>
				<xs:enumeration value="15"/>
				<xs:enumeration value="16"/>
				<xs:enumeration value="17"/>
				<xs:enumeration value="18"/>
				<xs:enumeration value="19"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="20"/>
				<xs:enumeration value="21"/>
				<xs:enumeration value="22"/>
				<xs:enumeration value="23"/>
				<xs:enumeration value="24"/>
				<xs:enumeration value="25"/>
				<xs:enumeration value="26"/>
				<xs:enumeration value="27"/>
				<xs:enumeration value="28"/>
				<xs:enumeration value="29"/>
				<xs:enumeration value="3"/>
				<xs:enumeration value="30"/>
				<xs:enumeration value="31"/>
				<xs:enumeration value="32"/>
				<xs:enumeration value="33"/>
				<xs:enumeration value="34"/>
				<xs:enumeration value="35"/>
				<xs:enumeration value="36"/>
				<xs:enumeration value="37"/>
				<xs:enumeration value="38"/>
				<xs:enumeration value="39"/>
				<xs:enumeration value="4"/>
				<xs:enumeration value="40"/>
				<xs:enumeration value="41"/>
				<xs:enumeration value="43"/>
				<xs:enumeration value="44"/>
				<xs:enumeration value="45"/>
				<xs:enumeration value="46"/>
				<xs:enumeration value="47"/>
				<xs:enumeration value="48"/>
				<xs:enumeration value="49"/>
				<xs:enumeration value="50"/>
				<xs:enumeration value="51"/>
				<xs:enumeration value="52"/>
				<xs:enumeration value="53"/>
				<xs:enumeration value="54"/>
				<xs:enumeration value="55"/>
				<xs:enumeration value="56"/>
				<xs:enumeration value="57"/>
				<xs:enumeration value="59"/>
				<xs:enumeration value="6"/>
				<xs:enumeration value="60"/>
				<xs:enumeration value="61"/>
				<xs:enumeration value="62"/>
				<xs:enumeration value="63"/>
				<xs:enumeration value="7"/>
				<xs:enumeration value="8"/>
				<xs:enumeration value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CoordenadasGUI">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="X"/>
				<xs:element ref="Y"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Casilla">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tipo"/>
				<xs:element ref="IndiceDestino"/>
				<xs:element ref="RondasSinJugar"/>
				<xs:element ref="RepetirTurno"/>
				<xs:element ref="CoordenadasGUI"/>
			</xs:sequence>
			<xs:attribute name="indice" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="10"/>
						<xs:enumeration value="11"/>
						<xs:enumeration value="12"/>
						<xs:enumeration value="13"/>
						<xs:enumeration value="14"/>
						<xs:enumeration value="15"/>
						<xs:enumeration value="16"/>
						<xs:enumeration value="17"/>
						<xs:enumeration value="18"/>
						<xs:enumeration value="19"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="20"/>
						<xs:enumeration value="21"/>
						<xs:enumeration value="22"/>
						<xs:enumeration value="23"/>
						<xs:enumeration value="24"/>
						<xs:enumeration value="25"/>
						<xs:enumeration value="26"/>
						<xs:enumeration value="27"/>
						<xs:enumeration value="28"/>
						<xs:enumeration value="29"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="30"/>
						<xs:enumeration value="31"/>
						<xs:enumeration value="32"/>
						<xs:enumeration value="33"/>
						<xs:enumeration value="34"/>
						<xs:enumeration value="35"/>
						<xs:enumeration value="36"/>
						<xs:enumeration value="37"/>
						<xs:enumeration value="38"/>
						<xs:enumeration value="39"/>
						<xs:enumeration value="4"/>
						<xs:enumeration value="40"/>
						<xs:enumeration value="41"/>
						<xs:enumeration value="42"/>
						<xs:enumeration value="43"/>
						<xs:enumeration value="44"/>
						<xs:enumeration value="45"/>
						<xs:enumeration value="46"/>
						<xs:enumeration value="47"/>
						<xs:enumeration value="48"/>
						<xs:enumeration value="49"/>
						<xs:enumeration value="5"/>
						<xs:enumeration value="50"/>
						<xs:enumeration value="51"/>
						<xs:enumeration value="52"/>
						<xs:enumeration value="53"/>
						<xs:enumeration value="54"/>
						<xs:enumeration value="55"/>
						<xs:enumeration value="56"/>
						<xs:enumeration value="57"/>
						<xs:enumeration value="58"/>
						<xs:enumeration value="59"/>
						<xs:enumeration value="6"/>
						<xs:enumeration value="60"/>
						<xs:enumeration value="61"/>
						<xs:enumeration value="62"/>
						<xs:enumeration value="63"/>
						<xs:enumeration value="7"/>
						<xs:enumeration value="8"/>
						<xs:enumeration value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== redeskako/Master-JAVA-UNED/alef/UNED_2014/antonio/Oca/xsd/TableroOca.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableroOca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/A126074/Escritorio/oca/BachelorDegree-master/workspace/OcaEnRed/xsd/tableroOca.xsd">
	<Casilla indice="1">
		<Tipo>1</Tipo>
		<IndiceDestino>1</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>80</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="2">
		<Tipo>2</Tipo>
		<IndiceDestino>2</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>160</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="3">
		<Tipo>2</Tipo>
		<IndiceDestino>3</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>200</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="4">
		<Tipo>2</Tipo>
		<IndiceDestino>4</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>240</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="5">
		<Tipo>3</Tipo>
		<IndiceDestino>9</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>280</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="6">
		<Tipo>4</Tipo>
		<IndiceDestino>12</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>320</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="7">
		<Tipo>2</Tipo>
		<IndiceDestino>7</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>360</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="8">
		<Tipo>2</Tipo>
		<IndiceDestino>8</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>400</X>
			<Y>460</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="9">
		<Tipo>3</Tipo>
		<IndiceDestino>14</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>460</X>
			<Y>430</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="10">
		<Tipo>2</Tipo>
		<IndiceDestino>10</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>380</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="11">
		<Tipo>2</Tipo>
		<IndiceDestino>11</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>340</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="12">
		<Tipo>4</Tipo>
		<IndiceDestino>6</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>300</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="13">
		<Tipo>2</Tipo>
		<IndiceDestino>13</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>260</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="14">
		<Tipo>3</Tipo>
		<IndiceDestino>18</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>220</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="15">
		<Tipo>2</Tipo>
		<IndiceDestino>15</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>470</X>
			<Y>180</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="16">
		<Tipo>2</Tipo>
		<IndiceDestino>16</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>485</X>
			<Y>140</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="17">
		<Tipo>2</Tipo>
		<IndiceDestino>17</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>480</X>
			<Y>100</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="18">
		<Tipo>3</Tipo>
		<IndiceDestino>23</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>475</X>
			<Y>50</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="19">
		<Tipo>5</Tipo>
		<IndiceDestino>19</IndiceDestino>
		<RondasSinJugar>2</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>440</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="20">
		<Tipo>2</Tipo>
		<IndiceDestino>20</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>380</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="21">
		<Tipo>2</Tipo>
		<IndiceDestino>21</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>340</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="22">
		<Tipo>2</Tipo>
		<IndiceDestino>22</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>300</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="23">
		<Tipo>3</Tipo>
		<IndiceDestino>27</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>260</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="24">
		<Tipo>2</Tipo>
		<IndiceDestino>24</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>220</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="25">
		<Tipo>2</Tipo>
		<IndiceDestino>25</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>180</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="26">
		<Tipo>6</Tipo>
		<IndiceDestino>53</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>140</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="27">
		<Tipo>3</Tipo>
		<IndiceDestino>32</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>100</X>
			<Y>10</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="28">
		<Tipo>2</Tipo>
		<IndiceDestino>28</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>70</X>
			<Y>35</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="29">
		<Tipo>2</Tipo>
		<IndiceDestino>29</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>80</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="30">
		<Tipo>2</Tipo>
		<IndiceDestino>30</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>110</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="31">
		<Tipo>7</Tipo>
		<IndiceDestino>31</IndiceDestino>
		<RondasSinJugar>2</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>150</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="32">
		<Tipo>3</Tipo>
		<IndiceDestino>36</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>190</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="33">
		<Tipo>2</Tipo>
		<IndiceDestino>33</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>230</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="34">
		<Tipo>2</Tipo>
		<IndiceDestino>34</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>270</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="35">
		<Tipo>2</Tipo>
		<IndiceDestino>35</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>30</X>
			<Y>310</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="36">
		<Tipo>3</Tipo>
		<IndiceDestino>41</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>40</X>
			<Y>350</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="37">
		<Tipo>2</Tipo>
		<IndiceDestino>37</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>95</X>
			<Y>380</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="38">
		<Tipo>2</Tipo>
		<IndiceDestino>38</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>135</X>
			<Y>380</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="39">
		<Tipo>2</Tipo>
		<IndiceDestino>39</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>175</X>
			<Y>380</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="40">
		<Tipo>2</Tipo>
		<IndiceDestino>40</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>false</RepetirTurno>
		<CoordenadasGUI>
			<X>215</X>
			<Y>380</Y>
		</CoordenadasGUI>
	</Casilla>
	<Casilla indice="41">
		<Tipo>3</Tipo>
		<IndiceDestino>45</IndiceDestino>
		<RondasSinJugar>0</RondasSinJugar>
		<RepetirTurno>true</RepetirTurno>
		<CoordenadasGUI>
			<X>255</X>
			<Y>380</Y>
		</CoordenadasGUI>
